### ISSUE TITLE
Notifications do not display

### ISSUE THREAD

**Issue by PfisterFactor** [h4llow3En/mac-notification-sys#33]
I made a minimal test program from one of the examples:
```rust
// main.rs
use mac_notification_sys::*;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    set_application("com.apple.Terminal")?;

    send_notification(
        "Danger",
        &Some("Will Robinson"),
        "Run away as fast as you can",
        &None,
    )?;

    Ok(())
}
```
Running the program doesn't produce a notification, on both debug and release mode.
I'm on a M1 Macbook Pro (2021, 14-inch) with Rust 1.58.
Compiling on stable-aarch64-apple-darwin or stable-x86_64-apple-darwin produces the same results.

**Comment by PfisterFactor** [comment]
I saw this issue #10 and tried testing it with https://github.com/Pandawan/mac-notification-sys/tree/usernotifications and got the same result.
```toml
[dependencies]
mac-notification-sys = { git = "https://github.com/Pandawan/mac-notification-sys.git", branch="usernotifications" }
```
